### ISSUE TITLE
jot is already an existing command in BSD and on the Mac

### ISSUE THREAD

**Issue by petdance** [schollz/gojot#94]
https://www.freebsd.org/cgi/man.cgi?jot(1)

```
$ jot 
usage: jot [-cnr] [-b word] [-w word] [-s string] [-p precision]
           [reps [begin [end [s]]]]
$ which jot
/usr/bin/jot
$ uname -a
Darwin parker.local 16.1.0 Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64 x86_64
```

**Comment by schollz** [comment]
Ugh! Any suggestions on a new name? jrnl and ntbk are already taken as well

**Comment by petdance** [comment]
No idea, sorry.  I just saw it mentioned on reddit and thought I'd let you know.

**Comment by bkhl** [comment]
iota?

**Comment by SamHH** [comment]
Suggestion: `iota`

There is a package with this name already but I think it's small enough that it doesn't matter to be honest.
